### ISSUE TITLE
Symfony 5.0 issue

### ISSUE THREAD

**Issue by sela** [sci3ma/sf4grumphp#13]
I tried to add it to a project with Symfony 5.0 and got the following error:

-   Problem 1

    - sci3ma/symfony-grumphp v3.0.0 requires povils/phpmnd ^2.1 -> satisfiable by povils/phpmnd[v2.1.0, v2.2.0].
    - sci3ma/symfony-grumphp v3.0.1 requires povils/phpmnd ^2.1 -> satisfiable by povils/phpmnd[v2.1.0, v2.2.0].
    - povils/phpmnd v2.2.0 requires symfony/console ^4.0 -> no matching package found.
    - povils/phpmnd v2.1.0 requires symfony/console ^4.0 -> no matching package found.
    - Installation request for sci3ma/symfony-grumphp ^3.0 -> satisfiable by sci3ma/symfony-grumphp[v3.0.0, v3.0.1].

**Comment by marcinharasim** [comment]
@sela unfortunately it's povils/phpmnd issue. There are still few pending PRs:
https://github.com/povils/phpmnd/pull/102
https://github.com/povils/phpmnd/pull/103
https://github.com/povils/phpmnd/pull/105
which will update dependencies. So we need to wait.

**Comment by sela** [comment]
thanks, but out of the box without forking your code you can't use it now. maybe best to remove the phpmnd? or use a tag one for symfony 4 and another one for symfony 5? I just tried with something I had to write and the code was in symfony 5.

**Comment by marcinharasim** [comment]
Thanks. I'll think about it. Maybe they'll merge those PRs in next few days.

**Comment by marcinharasim** [comment]
@sela https://github.com/povils/phpmnd/pull/105 has been merged. Shouldn't be any issues with Symfony 5 and phpmnd now
