### ISSUE TITLE
Upgrade grumphp version

### ISSUE THREAD

**Issue by omrqs** [sci3ma/sf4grumphp#14]
Many problems with deprecated code are resolved on latest version of grumphp. [For example](https://github.com/phpro/grumphp/blob/v0.18.0/src/Configuration/GrumPHP.php)

Using with symfony version 5.1 to many messages.

Thanks for all!

**Comment by marcinharasim** [comment]
Thanks @omrqs 
I'll look in this asap.

**Comment by marcinharasim** [comment]
Hey @omrqs sorry for delay but I had to wait for PR https://github.com/phpro/grumphp/pull/806 to be merged.
Here's v3.1.0 now: https://github.com/sci3ma/symfony-grumphp/releases/tag/v3.1.0
Update symfony-grumphp `./vendor/bin/symfony-grumphp install` then merge changes from your configurations files (phpunit.xml.dist, grumphp.yml, phpstan.neon) to new ones.
