### ISSUE TITLE
Dependency sensiolabs/security-checker is abandoned

### ISSUE THREAD

**Issue by omrqs** [sci3ma/sf4grumphp#15]
Package abandoned needs remove from grumphp.
![image](https://user-images.githubusercontent.com/1513178/108253242-50a48a80-7138-11eb-9cc3-1752847d02d7.png)

Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.

**Comment by marcinharasim** [comment]
Thanks @omrqs . I was waiting for GrumPHP to merge proper PRs. 
I decided to use  Enlightn Security Checker due to `fabpot/local-php-security checker` licensing issues: https://github.com/phpro/grumphp/pull/870
Here's the new release: https://github.com/sci3ma/symfony-grumphp/releases/tag/v3.2.0
